import {
  pgTable,
  uuid,
  text,
  numeric,
  timestamp,
  pgEnum,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { meters } from "./meters";
import { transactions } from "./transactions";

// Token type enum
export const tokenTypeEnum = pgEnum("token_type", [
  "credit",
  "clear_tamper",
  "set_power_limit",
  "key_change",
  "clear_credit",
]);

// Generated by enum
export const generatedByEnum = pgEnum("generated_by", [
  "system",
  "admin",
  "landlord",
]);

export const generatedTokens = pgTable("generated_tokens", {
  id: uuid("id").primaryKey().defaultRandom(),
  meterId: uuid("meter_id")
    .notNull()
    .references(() => meters.id, { onDelete: "restrict" }),
  transactionId: uuid("transaction_id").references(() => transactions.id, {
    onDelete: "restrict",
  }), // Nullable - e.g., null for Tamper tokens
  token: text("token").notNull(), // 20-digit STS token
  tokenType: tokenTypeEnum("token_type").notNull(),
  value: numeric("value", { precision: 12, scale: 4 }), // kWh for credit tokens, null for others
  generatedBy: generatedByEnum("generated_by").notNull().default("system"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const generatedTokensRelations = relations(
  generatedTokens,
  ({ one }) => ({
    meter: one(meters, {
      fields: [generatedTokens.meterId],
      references: [meters.id],
    }),
    transaction: one(transactions, {
      fields: [generatedTokens.transactionId],
      references: [transactions.id],
    }),
  })
);

// Types
export type GeneratedToken = typeof generatedTokens.$inferSelect;
export type NewGeneratedToken = typeof generatedTokens.$inferInsert;
